"""
tools/generate_report.py
Stage 3 — report_agent tool

Generates a markdown security report from aggregated scores.
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, List

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
log = logging.getLogger(__name__)


def generate_report(input_path: str, output_path: str, top_n: int = 10) -> Dict:
    """Generate DNS exfiltration detection report in markdown format."""
    input_file = Path(input_path)
    if not input_file.exists():
        log.error(f"File not found: {input_path}")
        return {"error": "file_not_found", "path": str(input_path)}

    log.info(f"Reading scores: {input_path}")
    with open(input_file, "r") as f:
        scores = json.load(f)

    total = len(scores)
    suspected = [s for s in scores if s["verdict"] == "suspected"]
    suspected_count = len(suspected)

    # Top suspicious domains
    top_domains = scores[:top_n]

    # Source breakdown
    sources = {}
    for s in scores:
        src = s.get("source", "unknown")
        sources[src] = sources.get(src, 0) + 1

    # Generate markdown
    report_lines = [
        "# DNS Exfiltration Detection Report",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        f"- **Total DNS queries analyzed:** {total:,}",
        f"- **Suspected exfiltration attempts:** {suspected_count:,} ({suspected_count/total*100:.1f}%)",
        f"- **Detection threshold:** 0.6 (combined score)",
        "",
        "---",
        "",
        f"## Top {top_n} Suspicious Domains",
        "",
        "| Rank | Domain | Entropy | DGA | Embed | Combined | Verdict |",
        "|------|--------|---------|-----|-------|----------|---------|"
    ]

    for i, domain in enumerate(top_domains, 1):
        report_lines.append(
            f"| {i} | `{domain['domain']}` | {domain['entropy_score']:.2f} | "
            f"{domain['dga_score']:.2f} | {domain['embed_score']:.2f} | "
            f"**{domain['combined_score']:.2f}** | {domain['verdict']} |"
        )

    report_lines.extend([
        "",
        "---",
        "",
        "## Score Breakdown",
        "",
        "### Detection Methods",
        "",
        "1. **Entropy Analysis (30% weight)**",
        "   - Measures randomness in subdomain characters",
        "   - High entropy → random hex/base64 encoding",
        "",
        "2. **DGA Classification (40% weight)**",
        "   - RandomForest ML classifier with 7 features",
        "   - Detects Domain Generation Algorithm patterns",
        "",
        "3. **Embedding Similarity (30% weight)**",
        "   - TF-IDF character n-grams + K-NN",
        "   - Distance from benign reference set",
        "",
        "### Source Distribution",
        ""
    ])

    for src, count in sources.items():
        report_lines.append(f"- **{src}:** {count:,} queries ({count/total*100:.1f}%)")

    report_lines.extend([
        "",
        "---",
        "",
        "## Recommendations",
        "",
        "1. **Immediate Actions:**",
        f"   - Block or investigate {suspected_count} suspected domains",
        "   - Review source IPs of high-score queries",
        "   - Check DNS logs for data encoding patterns",
        "",
        "2. **Long-term Measures:**",
        "   - Implement DNS query rate limiting",
        "   - Deploy DNS firewall rules",
        "   - Monitor subdomain entropy in real-time",
        "",
        "---",
        "",
        "*Report generated by DNS Exfiltration Detector*",
        "*Multi-agent ML pipeline with parallel scoring*",
        ""
    ])

    # Write report
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(report_lines))

    log.info(f"Report generated → {output_file}")

    return {
        "total_queries": total,
        "suspected_count": suspected_count,
        "report_file": str(output_file)
    }


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 3:
        print("Usage:")
        print("  python generate_report.py <scores_json> <output_md> [top_n]")
        print()
        print("Example:")
        print("  python generate_report.py data/output/scores.json data/output/exfil_report.md 10")
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2]
    top_n = int(sys.argv[3]) if len(sys.argv) > 3 else 10

    result = generate_report(input_path, output_path, top_n)

    if "error" not in result:
        print(f"[OK] Analyzed {result['total_queries']} queries")
        print(f"[OK] Found {result['suspected_count']} suspected domains")
        print(f"[OK] Report: {result['report_file']}")
    else:
        print(f"[ERROR] {result}")
        sys.exit(1)
